Packit enablement
InfrastructureServices/dnsconfd pull request #1
Opened 2023-11-02 15:16 UTC by pemensik

Simple changes to prepare packit building

2023-11-02 15:18 UTC, pemensik commented
I have created COPR build for this repository, but without automation watching commits.

2023-12-15 13:04 UTC, TomasKorbar requested changes
Review finished. When my comments are resolved please squash the commits.

2023-12-15 13:04 UTC, TomasKorbar commented on tests/build_package.sh
> -cp ./LICENSE distribution/LICENSE
Adding LICENSE symlink is a cool trick! Just needed this change to not break the testsuite.

2023-12-16 00:03 UTC, pemensik commented on .copr/Makefile
> +	if test -n "$(root)"; then cd $(root); fi && pwd && packit srpm --output=$(outdir)
But I have empty Subdirectory in copr project empty in the end, so yes, this should not be necessary anymore. I expect official packit enablement might be different anyway.

2023-12-19 12:37 UTC, TomasKorbar commented on .copr/Makefile
> +	if test -n "$(root)"; then cd $(root); fi && pwd && packit srpm --output=$(outdir)
Alright, so accept the change please and resolve the conversation.

2023-12-19 12:38 UTC, TomasKorbar commented on tests/build_package.sh
> -cp ./LICENSE distribution/LICENSE
Alright. That sounds like you accept the change so i will resolve this conversation.

2023-12-21 09:42 UTC, TomasKorbar approved these changes

2023-12-21 09:44 UTC, merged