Make dnsconfd able to handle unbound start failure
InfrastructureServices/dnsconfd pull request #17
Opened 2024-01-22 14:26 UTC by TomasKorbar

After 3 attempts to verify Unbound's status, the plugin will notify main loop to stop handling events and exit.

2024-01-29 20:33 UTC, pemensik requested changes

2024-01-29 20:33 UTC, pemensik commented on dnsconfd/dnsconfd_context.py
> +            interface.connect_to_signal("JobRemoved", self._service_start_finished)
Similar to start method above, this needs parameters passed to the call. ``"JobRemoved"`` and ``self._service_start_finished`` should be parameters. But I think the callback should be named self._on_job_removed after signal name. What we do in that signal should be commented in the handler or calling other methods from context, but function name should be named after event triggering it.

2024-01-29 20:33 UTC, pemensik commented on distribution/dnsconfd.service.d-unbound.conf
> +ExecStopPost=/bin/bash -c "dnsconfd --dbus-name=org.freedesktop.resolve1 reload --plugin unbound || true"
We want to be notified about what *service* has stopped. The daemon needs to know which service name belongs to each plugin. Please remove ``|| true`` and use leading ``-``. I would modify it to: ``ExecStopPost=-/usr/sbin/dnsconfd  notify --stopped %n``.
We want to report here what happened, not what we will do with that information. Service name will be read from config file or environment. Repeating it in every subcommand is not desired.

2024-01-29 20:33 UTC, pemensik commented on dnsconfd/cli_commands.py
> +            exit(1)
No, not like this. We need method like _fatal(reason), which might require asynchronous call to be done before stopping. _stop_execution should be used here, but with some constant instead of numbers filled in. We need also document return values anyway.

2024-01-29 20:33 UTC, pemensik commented on dnsconfd/dnsconfd_context.py
> +    def __init__(self, object_path, bus_name, config: dict, main_loop):
Why is main_loop passed into the context? Why it is not created during __init__() and then we do not offer self.run() method to call from dnsconfd binary? It does not seem to me we should prepare it this way, unless this class is not primary handler for main thread loop.

2024-01-30 08:40 UTC, TomasKorbar commented on dnsconfd/dnsconfd_context.py
> +        lgr.info(f"Starting unbound")
ah remnant of transition of this code from UnboundManager. Will fix.

2024-01-30 08:46 UTC, TomasKorbar commented on dnsconfd/dnsconfd_context.py
> +            interface.connect_to_signal("JobRemoved", self._service_start_finished)
Renamed. Unfortunately this can not be parametrized, because we have to connect to signal sooner than we submit start job, so we do not miss the signal. That is why _start_jobs dictionary exists, it holds pairs of start jobs and managers that should be used after.

2024-01-30 09:09 UTC, TomasKorbar commented on distribution/dnsconfd.service.d-unbound.conf
> +ExecStopPost=/bin/bash -c "dnsconfd --dbus-name=org.freedesktop.resolve1 reload --plugin unbound || true"
Leading `-` added. Reload is meant to be general command, i do not think that slipping into adding notifications about events into DBUS API is a good practice. API should stay as a collection of commands, i do not argue that this is not ideal. Ideal would be to listen to DBUS signal notifying us about change of unbound's state. Still this is a good compromise between not having the ideal solution and using command that can be still used manually.
I am not sure whether replacing `unbound` with `%n` is useful here, as you still need to implicitly pair service with its plugin by placing this file in the right location, thus placing `%n` here just adds one more required step in dnsconfd when we are handling the request.

2024-01-30 09:16 UTC, TomasKorbar commented on dnsconfd/cli_commands.py
> +            exit(1)
There is no `_stop_execution`, because we are not in a code that is handled by a dbus exported object. This is called by `bin/dnsconfd:19`
```
    # This ensures that proper handler is called if command is provided, else
    # noop and execution returns here
    args.func()
```
and it is easier to exit here with a value then doing the same thing in main module as the result would be the same.
Yeah exit values should be documented and proper constant values added. Will handle that in a separate PR.

2024-01-30 09:53 UTC, TomasKorbar commented on dnsconfd/dnsconfd_context.py
> +    def __init__(self, object_path, bus_name, config: dict, main_loop):
good idea, right now there is no reason why not move the loop inside of the context.

2024-01-30 10:39 UTC, pemensik commented on bin/dnsconfd
> +    ctx = DnsconfdContext("/org/freedesktop/resolve1", name, vars(args), loop)
Why do we create ``name`` here, when we can create it inside DnsconfdContext constructor from ``vars(args)`` later. We will have there everything needed, just complicates it here. The same with loop passed into it, we use no parameter for it before passing it further.

2024-01-31 09:02 UTC, TomasKorbar commented
/packit test

2024-01-31 15:04 UTC, merged